### ISSUE TITLE
Canvas使用Screen Space-Camera模式后无法正常显示

### ISSUE THREAD

**Issue by vihist** [warmtrue/WDataTable#1]
你好，使用Screen Space-Camera模式后，table被放大到整个画布上了。如何解决此问题呢？

**Comment by warmtrue** [comment]
已经修改了，更新测试下





在 2018-04-24 09:59:27，"vihist" <notifications@github.com> 写道：


你好，使用Screen Space-Camera模式后，table被放大到整个画布上了。如何解决此问题呢？
