### ISSUE TITLE
你好，能添加AddRow，DelRow接口吗？

### ISSUE THREAD

**Issue by sericaer** [warmtrue/WDataTable#2]
在程序运行中可能会增加数据或者删除数据，对应的能否添加AddRow，DelRow接口吗？

**Comment by warmtrue** [comment]
最新的 DynamicData 场景里有相关例子。 数据层操作后触发 UpdateData 即可

**Comment by warmtrue** [comment]
> 在程序运行中可能会增加数据或者删除数据，对应的能否添加AddRow，DelRow接口吗？

最新的 DynamicData 场景里有相关例子。 数据层操作后触发 UpdateData 即可

**Comment by sericaer** [comment]
thx!
